# Generated by Django 3.1.7 on 2021-09-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='access_time_from',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
