# Generated by Django 3.1.7 on 2021-09-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payment', '0002_auto_20210920_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='access_time_from',
            field=models.DateTimeField(),
        ),
    ]
