# Generated by Django 3.1.7 on 2021-09-20 20:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payment', '0003_auto_20210920_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSubscribedUser',
            fields=[
                ('subscribed_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.IntegerField(blank=True, default=0, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('pwd', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(default=0)),
                ('subscribed_date', models.DateTimeField(default=datetime.datetime.now)),
                ('expiry_date', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='paypal_payment.plan')),
            ],
            options={
                'verbose_name': 'PlanSubscribedUser',
                'verbose_name_plural': '2- Subscribed User',
            },
        ),
    ]
