# Generated by Django 3.1.7 on 2021-09-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payment', '0006_viewplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='s3control',
            fields=[
                ('s3_id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
