# Generated by Django 3.2 on 2022-05-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payment', '0008_auto_20210923_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewplan',
            name='log_status',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
