# Generated by Django 3.2 on 2022-05-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payment', '0010_plansubscribeduser_log_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration_day',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
