# Generated by Django 3.1.7 on 2021-04-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssf_id', models.IntegerField()),
                ('vendor_id', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('desc', models.TextField(blank=True, null=True)),
                ('featured_desc', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('duration', models.FloatField(null=0)),
                ('record_date', models.DateTimeField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('original_format', models.CharField(blank=True, max_length=100, null=True)),
                ('views', models.IntegerField()),
                ('rated_by', models.IntegerField()),
                ('rating', models.FloatField()),
                ('producer', models.CharField(blank=True, max_length=100, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('consultant', models.CharField(blank=True, max_length=100, null=True)),
                ('quote', models.CharField(blank=True, max_length=100, null=True)),
                ('quoate_author', models.CharField(blank=True, max_length=100, null=True)),
                ('quoate_location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
