# Generated by Django 3.1.7 on 2021-08-20 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ssftemp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('preslug', models.CharField(default='1', max_length=200)),
                ('content', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body_processed', models.BooleanField(default=False)),
                ('last_processed_date', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Blog Page',
                'verbose_name_plural': 'Blog Pages',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssf_id', models.IntegerField()),
                ('access_time_from', models.IntegerField()),
                ('access_time_to', models.IntegerField()),
                ('price', models.FloatField()),
                ('package_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField()),
                ('isdvd', models.IntegerField()),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(default='Group', max_length=100)),
            ],
            options={
                'verbose_name': 'Package Plan',
                'verbose_name_plural': '1-  Package Plan',
            },
        ),
        migrations.CreateModel(
            name='SubscribedUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('ssf_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('fname', models.CharField(blank=True, max_length=100, null=True)),
                ('lname', models.CharField(blank=True, max_length=100, null=True)),
                ('bdate', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('aboutme', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=1000, null=True)),
                ('town', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('zip', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('video_viewed', models.IntegerField(default=0)),
                ('profile_viewed', models.IntegerField(default=0)),
                ('watched_video', models.IntegerField(default=0)),
                ('addtime', models.CharField(blank=True, max_length=100, null=True)),
                ('logintime', models.CharField(blank=True, max_length=100, null=True)),
                ('account_status', models.CharField(blank=True, max_length=100, null=True)),
                ('subscribed', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'SubscribedUser',
                'verbose_name_plural': '2- Subscribed User',
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('ssf_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('parent', models.IntegerField(default=0)),
                ('desc', models.TextField(blank=True, null=True)),
                ('video_cat_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'VideoCategory',
                'verbose_name_plural': '5- Videos Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': '4- Videos'},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='quoate_author',
            new_name='quote_location',
        ),
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='quoate_location',
        ),
        migrations.AddField(
            model_name='video',
            name='quote_author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='consultant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='director',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='producer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='record_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='ssf_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
        migrations.CreateModel(
            name='VideoCategoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_category_c', to='ssftemp.videocategory')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_category_v', to='ssftemp.video')),
            ],
            options={
                'verbose_name': 'Video Category Map',
                'verbose_name_plural': '6 Video Category Mapping',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_fav_s', to='ssftemp.subscribeduser')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_fav_v', to='ssftemp.video')),
            ],
            options={
                'verbose_name': 'User Favorite',
                'verbose_name_plural': '7- User Favorite Videos',
            },
        ),
        migrations.CreateModel(
            name='SubscribedUserPlanMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssf_id', models.IntegerField()),
                ('exp_date', models.IntegerField()),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_plan_map_p', to='ssftemp.plan')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_plan_map_s', to='ssftemp.subscribeduser')),
                ('vod_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_plan_map_vod_video', to='ssftemp.video')),
            ],
            options={
                'verbose_name': 'Subscriber Plan Map',
                'verbose_name_plural': '3- Subscribed User Plan Mapping',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssf_id', models.IntegerField()),
                ('comment', models.TextField()),
                ('addtime', models.IntegerField()),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vid_com_s', to='ssftemp.subscribeduser')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vid_com_v', to='ssftemp.video')),
            ],
            options={
                'verbose_name': 'Video Comment',
                'verbose_name_plural': '8- Video Comments',
            },
        ),
    ]
