# Generated by Django 3.1.7 on 2021-08-20 23:22

from django.db import migrations, models
import ssftemp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssftemp', '0002_auto_20210821_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=ssftemp.models.get_file_path, verbose_name='Video content'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
