# Generated by Django 3.1.7 on 2021-08-20 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssftemp', '0003_auto_20210821_0452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Blog Page', 'verbose_name_plural': '9- Blog Pages'},
        ),
    ]
