# Generated by Django 3.1.7 on 2021-08-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title_logo_image', models.ImageField(blank=True, null=True, upload_to='project_details/')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='project_details/')),
                ('slider1_image', models.ImageField(blank=True, null=True, upload_to='project_details/')),
                ('slider2_image', models.ImageField(blank=True, null=True, upload_to='project_details/')),
                ('slider3_image', models.ImageField(blank=True, null=True, upload_to='project_details/')),
                ('slider4_image', models.ImageField(blank=True, null=True, upload_to='project_details/')),
                ('slider5_image', models.ImageField(blank=True, null=True, upload_to='project_details/')),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
