# Generated by Django 3.1.7 on 2021-08-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0002_project_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='about_logo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='about_slider1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='about_slider2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='about_slider3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='about_slider4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='about_slider5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_image/'),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='slider1_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_image/'),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='slider2_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_image/'),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='slider3_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_image/'),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='slider4_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_image/'),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='slider5_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_image/'),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='title_logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_image/'),
        ),
    ]
