# Generated by Django 3.1.7 on 2021-08-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0003_auto_20210829_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blog_image/')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('published', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
