# Generated by Django 3.1.7 on 2021-08-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0004_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='hit_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
