# Generated by Django 3.1.7 on 2021-09-02 15:15

from django.db import migrations, models
import django.db.models.deletion
import ssf.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0006_auto_20210831_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'VideoCategory',
                'verbose_name_plural': '3- Videos Categories',
            },
        ),
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_id', models.IntegerField(blank=True, default=0, null=True)),
                ('title', models.CharField(max_length=500)),
                ('video', models.FileField(blank=True, null=True, upload_to=ssf.models.get_file_path, verbose_name='Video content')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='poster_image/')),
                ('desc', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, default=0, null=True)),
                ('record_date', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('rated_by', models.IntegerField(blank=True, default=0, null=True)),
                ('rating', models.FloatField(blank=True, default=0, null=True)),
                ('producer', models.TextField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('video_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VideoCategory', to='ssf.videocategory')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': '4- Videos',
                'db_table': 'VideoUpload',
            },
        ),
    ]
