# Generated by Django 3.1.7 on 2021-09-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0007_videocategory_videoupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoupload',
            name='views',
        ),
        migrations.AddField(
            model_name='videoupload',
            name='hit_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='views'),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True),
        ),
    ]
