# Generated by Django 3.1.7 on 2021-09-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0009_videoupload_poster_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
