# Generated by Django 3.1.7 on 2021-09-02 22:11

import django.core.validators
from django.db import migrations, models
import ssf.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0010_auto_20210903_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=ssf.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Video content'),
        ),
    ]
