# Generated by Django 3.1.7 on 2021-09-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0012_auto_20210903_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='about_slider6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='slider1_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='slider2_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='slider3_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='slider4_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='slider5_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='slider6_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_image/'),
        ),
        migrations.AddField(
            model_name='project_details',
            name='slider6_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='title_logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
