# Generated by Django 3.1.7 on 2021-09-06 23:10

import django.core.validators
from django.db import migrations, models
import ssf.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0013_auto_20210903_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to=ssf.models.get_poster_path),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=ssf.models.get_video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'flv'])], verbose_name='Video content'),
        ),
    ]
