# Generated by Django 3.1.7 on 2021-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0014_auto_20210907_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
