# Generated by Django 3.1.7 on 2021-09-09 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0015_videoupload_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='VideoSubCategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=100)),
                ('sub_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VideoSubCategory', to='ssf.videocategory')),
            ],
            options={
                'verbose_name': 'VideoSubCategory',
                'verbose_name_plural': '2- Videos Sub Categories',
            },
        ),
    ]
