# Generated by Django 3.1.7 on 2021-09-09 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0016_auto_20210909_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='sub_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VideoSubCategory', to='ssf.videosubcategory'),
        ),
    ]
