# Generated by Django 3.1.7 on 2021-09-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0018_auto_20210923_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='about_default_poster',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='about_error',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='default_poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_image/'),
        ),
        migrations.AddField(
            model_name='project_details',
            name='default_poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='error_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_image/'),
        ),
        migrations.AddField(
            model_name='project_details',
            name='error_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
