# Generated by Django 3.1.7 on 2021-09-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0019_auto_20210928_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocategory',
            name='slug',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
