# Generated by Django 3.1.7 on 2021-10-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0023_auto_20210928_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosubcategory',
            name='slug',
            field=models.SlugField(max_length=500, null=True, unique=True),
        ),
    ]
