# Generated by Django 3.1.7 on 2021-10-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0024_videosubcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='home_active',
            field=models.BooleanField(default=True),
        ),
    ]
