# Generated by Django 3.1.1 on 2022-02-11 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ssf', '0026_subscriptiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('subscription_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_type', to='ssf.subscriptiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Subscription',
                'verbose_name_plural': 'Email Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, choices=[('video', 'video'), ('blog', 'blog')], default='video', max_length=50, null=True)),
                ('content_id', models.IntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, choices=[('like', 'like'), ('dislike', 'dislike'), ('favorite', 'favorite')], default='like', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_fav_s', to='ssf.emailsubscription')),
            ],
            options={
                'verbose_name': 'User Favorite',
                'verbose_name_plural': '7- User Favorite Videos',
            },
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, choices=[('video', 'video'), ('blog', 'blog')], default='video', max_length=50, null=True)),
                ('content_id', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='This is very nice.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vid_com_s', to='ssf.emailsubscription')),
            ],
            options={
                'verbose_name': 'Video Comment',
                'verbose_name_plural': '8- Video Comments',
            },
        ),
    ]
