# Generated by Django 3.1.1 on 2022-02-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0027_emailsubscription_usercomment_userfavoritevideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavoritevideo',
            old_name='label',
            new_name='thumb',
        ),
    ]
