# Generated by Django 3.1.1 on 2022-02-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0028_auto_20220211_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'VideoCategory', 'verbose_name_plural': '4- Blog Post'},
        ),
        migrations.AlterModelOptions(
            name='emailsubscription',
            options={'verbose_name': 'Email Subscription', 'verbose_name_plural': '6- Email Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='subscriptiontype',
            options={'verbose_name': 'Subscription Type', 'verbose_name_plural': '5- Subscription Types'},
        ),
        migrations.AlterModelOptions(
            name='videocategory',
            options={'verbose_name': 'VideoCategory', 'verbose_name_plural': '1- Videos Categories'},
        ),
        migrations.AlterModelOptions(
            name='videoupload',
            options={'verbose_name': 'Video', 'verbose_name_plural': '3- Videos'},
        ),
        migrations.RenameField(
            model_name='userfavoritevideo',
            old_name='thumb',
            new_name='label',
        ),
    ]
