# Generated by Django 3.1.7 on 2022-05-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0031_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='home_active',
            field=models.BooleanField(default=True),
        ),
    ]
