# Generated by Django 3.1.7 on 2022-05-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0032_usercomment_home_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoritevideo',
            name='fab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userfavoritevideo',
            name='label',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('dislike', 'dislike')], default='like', max_length=50, null=True),
        ),
    ]
