# Generated by Django 3.1.7 on 2022-05-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0033_auto_20220504_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoritevideo',
            name='label',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('dislike', 'dislike')], max_length=50, null=True),
        ),
    ]
