# Generated by Django 3.1.7 on 2022-05-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0034_auto_20220507_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoritevideo',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
