# Generated by Django 3.2 on 2022-05-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0036_auto_20220514_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desc',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
