# Generated by Django 3.2 on 2022-07-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0040_videoupload_ssf_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='ssf_poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='ssf_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
