# Generated by Django 3.2 on 2022-07-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf', '0041_auto_20220801_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='duration_str',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
